allow-lan: true
bind-address: 127.0.0.1
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 180.76.76.76
  - 1.1.1.1
  enable: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  ipv6: false
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  use-hosts: true
external-controller: 127.0.0.1:9090
geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
log-level: info
mixed-port: 7891
mode: rule
proxies:
proxy-groups:
- name: USER
  proxies:
    - AUTO
  type: select
- interval: 300
  name: AUTO
  proxies:
  type: url-test
  url: https://cp.cloudflare.com/generate_204

    
rules:
- DST-PORT,53,DIRECT
- DST-PORT,5353,DIRECT
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,USER
